### ISSUE TITLE
Scroll Sync between a markdown file and the preview window does not work

### ISSUE THREAD

**Issue by sengopal** [georgebrindeiro/scroll-sync#2]
When a *.md file and the preview window are kept opened. However, the toggle of "ScrollSync" does not scroll both the windows.

**Comment by mark-hahn** [comment]
Sorry.  Scroll-sync only works with two text files.  The preview window is not a text file.

I have a new package on my to-do list to specifically sync markdown with its preview as you wish.

**Comment by sengopal** [comment]
oh..Thats sad :( Could you point me to a good place on the code to look at this. I can try to create a pull request. Thanks again for the response.

**Comment by mark-hahn** [comment]
The crucial part of the scroll-sync package is the diffing of the text in the two files.  Markdown preview doesn't have a text buffer. It is markdown compiled to html.  I can't compare the original text to the html.

I have an idea for syncing markdown.  The idea is to render the markdown text into html off-screen but only render it up to the position in the visible text file.  Then I would look at the off-screen html height and scroll the preview to the same height.  This might be slow.

This would be very different than my current scroll-sync which is why I want it to be a new package.  I would be very grateful for help on any package.  I'll let you know when I start the new one.
